version: "3.8"

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - auth-service
      - election-service
      - option-service
      - vote-service
      - result-service
      - email-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "5004:5004"
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    networks:
      - app-network

  election-service:
    build: ./election-service
    ports:
      - "5001:5001"
    networks:
      - app-network

  option-service:
    build: ./option-service
    ports:
      - "5002:5002"
    networks:
      - app-network

  vote-service:
    build: ./vote-service
    ports:
      - "5005:5005"
    networks:
      - app-network

  result-service:
    build: ./result-service
    ports:
      - "5003:5003"
    networks:
      - app-network

  email-service:
    build: ./email-service
    ports:
      - "5006:5006"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
